switched to use correct unpkg domain for zxing lib
zxing-js/library pull request #475
Opened 2021-09-22 13:37 UTC by HeikoWitthoeft

switched to use correct url for xzing lib for the live demo
https://unpkg.com/@zxing/library@latest/umd/index.min.js

2021-11-12 21:36 UTC, rvalitov commented on docs/examples/qr-video/index.html
> +  <script type="text/javascript" src="https://unpkg.com/@zxing/library@0.18.6/umd/index.min.js"></script>
#483 uses `@latest` in all files. So I think it's not required to use a specific version.

2021-11-12 21:37 UTC, rvalitov requested changes

2021-11-12 21:37 UTC, rvalitov commented on docs/examples/qr-video/index.html
> +  <script type="text/javascript" src="https://unpkg.com/@zxing/library@0.18.6/umd/index.min.js"></script>
#483 uses @latest in all files. So I think it's not required to use a specific version.

2021-12-30 02:07 UTC, WIStudent commented
Latest should work again in version 0.19 (see https://github.com/zxing-js/library/pull/452) but unfortunately some broken tests prevented v0.19 from being pushed to npm.

2021-12-30 10:10 UTC, rvalitov commented
@WIStudent Thank you so much for reporting that. Can you please let me know if you could fix the related tests?

2021-12-30 12:05 UTC, WIStudent commented
@rvalitov Looking at the history of the "Continuous Integration" workflow it seems that the E2E test never ran successfully on github actions. https://github.com/zxing-js/library/actions/workflows/ci.yml

Back in summer I was researching some ways to scan QR codes in web, found @zxing/library, noticed that the demo page was broken, and created PR https://github.com/zxing-js/library/pull/452 to fix unpkg. But in the end I decided against using @zxing/library in my project. Just by coincidence I noticed now that the demo page is still broken despite https://github.com/zxing-js/library/pull/452 being merged.

So someone else more familiar with the codebase needs to look why the E2E tests are failing.

2021-12-30 12:31 UTC, rvalitov commented
@WIStudent thank you for you prompt response. I'm curious what package did you use in your project instead of this library?

2021-12-30 12:50 UTC, WIStudent commented
@rvalitov I was looking for a way to scan QR codes inside a [capactior](https://capacitorjs.com/) app and ended up using [@capacitor-community/barcode-scanner](https://www.npmjs.com/package/@capacitor-community/barcode-scanner) which does the scanning and processing in the native android/iOS part instead of the web part.

2021-12-30 18:12 UTC, rvalitov commented
@WIStudent Ok, got it, thank you!

2021-12-30 18:15 UTC, rvalitov commented
@werthdavid can you please look into this problem that library ver.0.19 is missing at npm? Perhaps, you could publish it there manually? I'm not familiar with the tests, but perhaps you could give some tips if it's easy to fix them or not? Or if the failing tests are really required or perhaps that's something old that could be deleted?

2022-01-04 07:55 UTC, werthdavid commented
@rvalitov it didn't publish to npm because the tests failed. I started commenting tests out on my machine but its really a lot I have to disable so the tests won't fail... not sure if that's a good idea imho. on the other hand the versions minor to 0.19 are not really working as well either. What do you mean? publish without tests?

2022-01-07 10:44 UTC, rvalitov commented
@werthdavid Yes, I suggest to publish without tests. At least this gives more freedom to end users and they can use the version they need by pinning to a specific version. So in case the version 0.19 is not good for someone, then they can stay with version 0.18. But now if a user needs version 0.19 then packaging it manually without using npm is a little more troublesome. So, a released 0.19 version in npm would help a lot.

2022-01-10 07:40 UTC, werthdavid commented
I hope v0.19.1 works

2022-01-18 17:02 UTC, rvalitov commented
@werthdavid Thank you! FYI, unfortunately I couldn't use and test the v0.19.1, because both the `ngx-scanner` and `browser` require and use `^0.18.5`, therefore the `npm` does not allow me to use v.0.19.1

2022-01-19 07:42 UTC, werthdavid commented
I can provide you a tgz file for testing if you want

2022-04-26 05:48 UTC, werthdavid commented
Should be fixed. Reopen if not

2022-04-26 05:48 UTC, closed without merging